### criar 

POST https://node-do-zero-0r4l.onrender.com/clientes
Content-Type: application/json

{
    "name": "Lucas Oliveira",
    "description": "Esse é o primeiro cliente"
}

### listar (?search=Lucas - para filtrar uma busca)

GET https://node-do-zero-0r4l.onrender.com/clientes

### atualizar 

PUT https://node-do-zero-0r4l.onrender.com/clientes/
Content-Type: application/json

{
    "name": "Lorena meu amor",
    "description": "Esse é o primeiro cliente"
}

### deletar

DELETE https://node-do-zero-0r4l.onrender.com/clientes/f9b5e598-df1d-4eba-8d0f-fda9d40da109